function dpf = get_dpf2017_06_10(in1,in2)
%GET_DPF2017_06_10
%    DPF = GET_DPF2017_06_10(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    11-Jun-2017 05:03:41

dxf = in2(1,:);
dyf = in2(2,:);
dzf = in2(3,:);
dpf = [dxf;dyf;dzf];
