function dpg = get_dpg2017_09_22(in1,in2)
%GET_DPG2017_09_22
%    DPG = GET_DPG2017_09_22(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    22-Sep-2017 20:46:08

dphif = in2(4,:);
dphit = in2(7,:);
dpsif = in2(6,:);
dthetaf = in2(5,:);
dthetat = in2(8,:);
dxf = in2(1,:);
dyf = in2(2,:);
dzf = in2(3,:);
phif = in1(4,:);
phit = in1(7,:);
psif = in1(6,:);
thetaf = in1(5,:);
thetat = in1(8,:);
t2 = thetaf-thetat;
t3 = cos(phif);
t4 = sin(psif);
t5 = cos(psif);
t6 = sin(phif);
t12 = pi.*(1.0./2.0);
t7 = -t12+thetaf;
t8 = cos(t7);
t9 = cos(t2);
t10 = phif-phit;
t11 = t4.*t6;
t13 = t3.*t5.*t8;
t14 = t11+t13;
t15 = cos(t10);
t16 = sin(t2);
t17 = sin(t10);
t18 = sin(t7);
t19 = t3.*t4;
t22 = t5.*t6.*t8;
t20 = t19-t22;
t21 = t9.*t14.*t17.*4.0;
t23 = t14.*t15.*t16.*4.0;
t24 = t5.*t16.*t17.*t18.*4.0;
t25 = t5.*t6;
t30 = t3.*t4.*t8;
t26 = t25-t30;
t27 = t3.*t5;
t28 = t4.*t6.*t8;
t29 = t27+t28;
t31 = t9.*t17.*t26.*4.0;
t32 = t4.*t9.*t15.*t18.*4.0;
t33 = t9.*t29.*4.0;
t34 = t4.*t16.*t17.*t18.*4.0;
t35 = t6.*t9.*t18.*4.0;
t36 = t3.*t15.*t16.*t18.*4.0;
t37 = t8.*t9.*t15.*4.0;
t38 = t3.*t9.*t17.*t18.*4.0;
dpg = [dxf+dthetat.*(t23+t24-t9.*t20.*4.0)-dthetaf.*(t23+t24-t9.*t20.*4.0-t5.*t8.*t9.*t17.*4.0-t5.*t6.*t16.*t18.*4.0+t3.*t5.*t9.*t15.*t18.*4.0)+dpsif.*(t16.*t29.*4.0+t9.*t15.*t26.*4.0-t4.*t9.*t17.*t18.*4.0)+dphit.*(t21-t5.*t9.*t15.*t18.*4.0)-dphif.*(t21+t14.*t16.*4.0-t9.*t15.*t20.*4.0-t5.*t9.*t15.*t18.*4.0);dyf-dphit.*(t31+t32)+dphif.*(t31+t32+t16.*t26.*4.0-t9.*t15.*t29.*4.0)+dpsif.*(t16.*t20.*4.0+t9.*t14.*t15.*4.0+t5.*t9.*t17.*t18.*4.0)+dthetat.*(t33+t34-t15.*t16.*t26.*4.0)-dthetaf.*(t33+t34-t15.*t16.*t26.*4.0-t4.*t8.*t9.*t17.*4.0-t4.*t6.*t16.*t18.*4.0+t3.*t4.*t9.*t15.*t18.*4.0);dzf-dphit.*(t37+t38)+dthetaf.*(t35+t36+t6.*t8.*t16.*4.0-t8.*t16.*t17.*4.0-t9.*t17.*t18.*4.0-t3.*t8.*t9.*t15.*4.0)-dthetat.*(t35+t36-t8.*t16.*t17.*4.0)+dphif.*(t37+t38+t3.*t16.*t18.*4.0+t6.*t9.*t15.*t18.*4.0)];
