function pf = get_pf2017_06_10(in1,in2)
%GET_PF2017_06_10
%    PF = GET_PF2017_06_10(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    11-Jun-2017 05:03:45

xf = in1(1,:);
yf = in1(2,:);
zf = in1(3,:);
pf = [xf;yf;zf];
