function pf = get_pf2017_09_27(in1,in2)
%GET_PF2017_09_27
%    PF = GET_PF2017_09_27(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    27-Sep-2017 17:07:38

xf = in1(1,:);
yf = in1(2,:);
zf = in1(3,:);
pf = [xf;yf;zf];
