function pg = get_pg2017_06_10(in1,in2)
%GET_PG2017_06_10
%    PG = GET_PG2017_06_10(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    11-Jun-2017 05:03:45

phif = in1(4,:);
phig = in1(9,:);
phit = in1(7,:);
psif = in1(6,:);
thetaf = in1(5,:);
thetag = in1(10,:);
thetat = in1(8,:);
xf = in1(1,:);
yf = in1(2,:);
zf = in1(3,:);
t2 = thetaf-thetat;
t3 = sin(t2);
t4 = pi.*(1.0./2.0);
t5 = t4+thetag-thetat;
t6 = sin(phif);
t7 = sin(psif);
t8 = cos(phif);
t9 = cos(psif);
t10 = cos(t2);
t11 = sin(t5);
t12 = phif-phig;
t13 = phif-phit;
t14 = cos(t12);
t15 = cos(t13);
t16 = cos(t5);
t17 = -t4+thetaf;
t18 = sin(t13);
t19 = sin(t12);
t20 = cos(t17);
t21 = t3.*4.0;
t22 = t10.*t16.*(2.1e1./2.0e2);
t23 = t3.*t11.*t14.*(2.1e1./2.0e2);
t24 = t21+t22+t23;
t25 = t18.*t19;
t37 = t10.*t14.*t15;
t26 = t25-t37;
t36 = t10.*t15.*4.0;
t38 = t11.*t26.*(2.1e1./2.0e2);
t39 = t3.*t15.*t16.*(2.1e1./2.0e2);
t27 = t36-t38-t39+2.3e1./2.0e2;
t28 = sin(t17);
t29 = t10.*t18.*4.0;
t30 = t15.*t19;
t31 = t10.*t14.*t18;
t32 = t30+t31;
t33 = t11.*t32.*(2.1e1./2.0e2);
t35 = t3.*t16.*t18.*(2.1e1./2.0e2);
t34 = t29+t33-t35;
pg = [xf+t27.*(t6.*t7+t8.*t9.*t20)+t24.*(t7.*t8-t6.*t9.*cos(pi.*(-1.0./2.0)+thetaf))+t9.*t28.*t34;yf-t24.*(t8.*t9+t6.*t7.*t20)-t27.*(t6.*t9-t7.*t8.*t20)+t7.*t28.*t34;zf+t20.*t34+t6.*t24.*t28-t8.*t27.*t28];
