function Q = get_QGenFloat(in1,in2,in3,in4)
%GET_QGENFLOAT
%    Q = GET_QGENFLOAT(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    20-Sep-2017 08:31:05

Fx = in3(1,:);
Fy = in3(2,:);
Fz = in3(3,:);
ax = in4(1,:);
ay = in4(2,:);
az = in4(3,:);
phif = in1(4,:);
psif = in1(6,:);
thetaf = in1(5,:);
t6 = pi.*(1.0./2.0);
t2 = -t6+thetaf;
t3 = sin(t2);
t4 = sin(phif);
t5 = cos(phif);
t7 = sin(psif);
t8 = cos(psif);
t9 = cos(t2);
t10 = t5.*t8;
t11 = t4.*t7.*t9;
t12 = t10+t11;
t13 = t4.*t8;
t14 = t13-t5.*t7.*t9;
t15 = t5.*t7;
t16 = t15-t4.*t8.*t9;
t17 = t4.*t7;
t18 = t5.*t8.*t9;
t19 = t17+t18;
Q = [Fx;Fy;Fz;-Fz.*(ay.*t3.*t5-az.*t3.*t4)+Fx.*(ay.*t19+az.*t16)-Fy.*(ay.*t14+az.*t12);-Fz.*(-ax.*t3+ay.*t4.*t9+az.*t5.*t9)-Fx.*(ax.*t8.*t9+ay.*t3.*t4.*t8+az.*t3.*t5.*t8)-Fy.*(ax.*t7.*t9+ay.*t3.*t4.*t7+az.*t3.*t5.*t7);Fx.*(-ay.*t12+az.*t14+ax.*t3.*t7)-Fy.*(ay.*t16-az.*t19+ax.*t3.*t8);0.0;0.0;0.0;0.0;0.0;0.0];
