function pg = get_pg2017_09_27(in1,in2)
%GET_PG2017_09_27
%    PG = GET_PG2017_09_27(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    27-Sep-2017 17:07:39

phif = in1(4,:);
phit = in1(7,:);
psif = in1(6,:);
thetaf = in1(5,:);
thetat = in1(8,:);
xf = in1(1,:);
yf = in1(2,:);
zf = in1(3,:);
t2 = thetaf-thetat;
t3 = sin(phif);
t4 = sin(psif);
t5 = cos(phif);
t6 = cos(psif);
t11 = pi.*(1.0./2.0);
t7 = -t11+thetaf;
t8 = cos(t7);
t9 = cos(t2);
t10 = phif-phit;
t12 = sin(t2);
t13 = cos(t10);
t14 = sin(t10);
t15 = sin(t7);
pg = [xf+t12.*(t4.*t5-t3.*t6.*t8).*4.0+t9.*t13.*(t3.*t4+t5.*t6.*t8).*4.0+t6.*t9.*t14.*t15.*4.0;yf-t12.*(t5.*t6+t3.*t4.*t8).*4.0-t9.*t13.*(t3.*t6-t4.*t5.*t8).*4.0+t4.*t9.*t14.*t15.*4.0;zf+t3.*t12.*t15.*4.0+t8.*t9.*t14.*4.0-t5.*t9.*t13.*t15.*4.0];
