function AddedMassFloat = set_AddedMassFloat2017_09_22(in1,in2,in3)
%SET_ADDEDMASSFLOAT2017_09_22
%    ADDEDMASSFLOAT = SET_ADDEDMASSFLOAT2017_09_22(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    22-Sep-2017 14:07:20

AddedMJfx = in3(4,:);
AddedMJfy = in3(5,:);
AddedMJfz = in3(6,:);
AddedMmfx = in3(1,:);
AddedMmfy = in3(2,:);
AddedMmfz = in3(3,:);
AddedMassFloat = reshape([AddedMmfx,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,AddedMmfy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,AddedMmfz,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,AddedMJfx,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,AddedMJfy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,AddedMJfz,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[12, 12]);
